#DIR = $(shell pwd)/app
#
#CONFIG_PATH = $(shell pwd)/config
#IDL_PATH = $(shell pwd)/idl
#BIN = $(shell pwd)/bin

MODULE := $(shell go list -m)

DIR = app
CONFIG_PATH = config
IDL_PATH = idl
BIN = bin

#SERVICES := gateway user favorite search_engine index_platform
SERVICES := gateway search_engine index_platform inverted_index
service = $(word 1, $@)



.PHONY: proto
proto:
	@for file in $(IDL_PATH)/*.proto; do \
		protoc -I $(IDL_PATH) $$file --go-grpc_out=$(IDL_PATH)/pb --go_out=$(IDL_PATH)/pb; \
	done
	@for file in $(shell find $(IDL_PATH)/pb/* -type f); do \
		protoc-go-inject-tag -input=$$file; \
	done

#.PHONY: $(SERVICES)
#$(SERVICES):
#	go build -o $(BIN)/$(service) $(DIR)/$(service)/cmd
#	$(BIN)/$(service)

.PHONY: $(SERVICES)
$(SERVICES):
	go build -o $(BIN)/$(service) $(MODULE)/$(DIR)/$(service)/cmd
	$(BIN)/$(service)